### ISSUE TITLE
Getting configuration invalid error after putting keymaster-basic.yaml file into packages folder

### ISSUE THREAD

**Issue by patdemko** [desertblade/Keymaster-Basic#1]
Not sure if this is something new with recent versions of Home Assistant and how the yaml files are named, but after putting the keymaster-basic.yaml file into the packages folder and checking the config I got the following error.  

invalid slug keymaster-basic (try keymaster_basic) for dictionary value @ data['packages']

![image](https://user-images.githubusercontent.com/11141892/231757152-2e8d13ab-cc04-4b7f-a763-8023a38f6a09.png)

Changing the filename to "keymaster_basic.yaml" stopped the error from showing up.

**Comment by desertblade** [comment]
Good catch. Updated to the name that Home Assistant likes.

Thanks!
